name: CI

on:
  push:
    branches:
      - main
  pull_request:

# Needed for nx-set-shas within nx-cloud-main.yml, when run on the main branch
permissions:
  actions: read
  contents: read

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.13.1
    with:
      node-version: 20
      main-branch-name: main
      number-of-agents: 3
      init-commands: |
        npx nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
        touch apps/trucking-kit/src/amplifyconfiguration.json
        echo {  "aws_project_region": "us-east-1",  "aws_cognito_identity_pool_id": "us-east-1:c167708c-a7aa-4d7d-a43f-5093ff6111d3",  "aws_cognito_region": "us-east-1",  "aws_user_pools_id": "us-east-1_rOHv3efMX",  "aws_user_pools_web_client_id": "7i6qvkn96lt7dinl6gh26gdtsh",  "oauth": {},  "aws_cognito_username_attributes": [    "EMAIL"  ],  "aws_cognito_social_providers": [],  "aws_cognito_signup_attributes": [    "EMAIL"  ],  "aws_cognito_mfa_configuration": "OFF",  "aws_cognito_mfa_types": [    "SMS"  ],  "aws_cognito_password_protection_settings": {    "passwordPolicyMinLength": 8,    "passwordPolicyCharacters": []  },  "aws_cognito_verification_mechanisms": [    "EMAIL"  ]} >> apps/trucking-kit/src/amplifyconfiguration.json
        cat apps/trucking-kit/src/amplifyconfiguration.json
        ls
        ls apps
        ls apps/trucking-kit
        ls apps/trucking-kit/src
      parallel-commands: |
        cat apps/trucking-kit/src/amplifyconfiguration.json
        npx nx-cloud record -- npx nx format:check
      parallel-commands-on-agents: |
        npx nx affected --target=lint --parallel=3
        npx nx affected --target=test --parallel=3 --ci --code-coverage
        cat apps/trucking-kit/src/amplifyconfiguration.json && npx nx affected --target=build --parallel=3

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.13.1
    with:
      number-of-agents: 3
